### ISSUE TITLE
Initial Meeting

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#1]
Let's figure out a time for this :)

**Comment by Burstaholic** [comment]
That Doodle site seems pretty nifty. We could also just say, "Who can't do Weds 11a?" (This was the best consensus from the last Doodle we did)

Danese clearly can't but it sounds like she's busy the whole week.

**Comment by Morgul** [comment]
My availability is:

Weekdays 10am to 4pm (CST), _except_:
- Tuesday 10am to 10:30am
- Thursday 10am to 10:30am

Weekends open.

**Comment by jasnell** [comment]
@mikeal ... who all should be in on this discussion?

**Comment by mikeal** [comment]
I've added them all to the team that runs this repo and many already participated in a doodle that went out before this repo went up, @dshaw can you paste the link to that doodle here?

**Comment by guyellis** [comment]
@mikeal That wasn't the doodle that I tried to send yesterday was it? @cianomaidin said that he pinged you about that yesterday.

**Comment by mikeal** [comment]
I thought there was already one up that dshaw did like last week?

Whatever, let's just start a new one and dump the link in here :)

**Comment by mikeal** [comment]
@mkdolan do the bylaws already account for a board representative elected by the individual membership? if not can we do this without altering the bylaws which is quite difficult as I understand it?

**Comment by rvagg** [comment]
> Repo to work out the system for individual membership in the foundation.

@mikeal can you clarify what this is all about?

**Comment by guyellis** [comment]
> let's just start a new one and dump the link in here :)

If the link were in here then the general public would be able to use it, wouldn't they?

**Comment by dshaw** [comment]
@mikeal The old Doodle is not worth anything. Old dates. Just create a new one.

**Comment by dshaw** [comment]
http://doodle.com/ktv4ypvy8g6ky4k9 @Burstaholic and @Morgul are already on this list.

**Comment by mkdolan** [comment]
I mentioned on the call yesterday this requires a bylaws change. I had setup the TSC Chair as the voice of the community, but an individual membership board seat would be a different Board seat that we didn’t factor in. It may not be that disruptive of a change, but let me do a litmus test with the team that’s been working on the drafts with us.

**Comment by mikeal** [comment]
@rvagg this grew out of the last advisory board meeting.

Basically, we have a placeholder for "individual members" signing up to be part of the foundation similar to what the Linux Foundation does. We hadn't figured out exactly how to administer that and what the benefits would be yet so I setup this repo to do it.

@danese recommends that we have a board seat elected by the individual membership to represent the wider community (more than just the TSC as the TSC already has a seat).

@mkdolan can the board invite this person to sit on the board in a non-voting capacity in the interim? It'll be a while before we get members signed up and do an election and if it's a few months until all this shakes out we may want to wait on this change in case there are any other small adjustments the board wants to make to the bylaws.

**Comment by mikeal** [comment]
@guyellis you wanna drive a new doodle to get this worked out?

**Comment by guyellis** [comment]
Here you go: https://doodle.com/gt2aickp7znysyam

**Comment by Morgul** [comment]
@guyellis That only has dates; don't we also need time of day available?

**Comment by guyellis** [comment]
@Morgul Doodle learner driver. Times added. Let me know how that looks to you. Feel free to give me more advice on Doodle.

**Comment by mikeal** [comment]
Is there a timezone set on these? I noticed that even after I changed my timezone none of the times shifted so I'm wondering if they are floating times or something.

**Comment by guyellis** [comment]
The help says that there should be an option but I think the help is out-of-date as there's no option that I could see when setting it up: http://support.doodle.com/customer/portal/articles/645367

My Doodle profile has my timezone set at MST Arizona which is what I assume it was set at.

**Comment by guyellis** [comment]
Turns out that you have to enable timezones when you first create a Doodle and can't add it afterwards. I've created a new one and updated the link above. Here it is again: https://doodle.com/gt2aickp7znysyam

**Comment by Morgul** [comment]
@guyellis Np.

Signed up on the latest one. :) All seems good, now.

**Comment by guyellis** [comment]
@Morgul - my apologies - I had to delete the other Doodle. New link above. Timezone enabled.

**Comment by Burstaholic** [comment]
So, looks like Tuesday morning or Wednesday noon? 

Wednesday is slightly better for Chris (Morgul) and I because we have a short internal meeting Tuesday that is supposed to end at 10, but it's always possible to run over a few minutes (not many though, due to room scheduling).

**Comment by guyellis** [comment]
@Burstaholic you're on Mountain Time right? So Wednesday noon is 2pm ET? Shall I close the Doodle with that day/time?

**Comment by Morgul** [comment]
We're CST, so 1pm EST.

**Comment by Burstaholic** [comment]
@guyellis With that correction, 12p CST/1p EST seems good to me!

**Comment by guyellis** [comment]
I closed the poll and picked that time. Let me know if I got it right. I'm in AZ (no daylight savings) and couldn't work out if the calendar understood that AZ is currently on PT and not MT as the calendar seemed to indicate.

**Comment by guyellis** [comment]
Calendar meeting invites sent to @Burstaholic @Morgul @mikeal @cianomadin

Who else needs one?

**Comment by jasnell** [comment]
Raises hand.

**Comment by guyellis** [comment]
@jasnell en route.

**Comment by Danese** [comment]
Either way I'll still be in Europe, so joining by phone. Need an invite please.

D

**Comment by guyellis** [comment]
@Danese done.

**Comment by mikeal** [comment]
We can use my Uber Conference for this www.uberconference.com/mikeal

**Comment by guyellis** [comment]
Meeting held - thanks for attending everyone!
