### ISSUE TITLE
Nominations for the 2016 election.

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#12]
If you wish to run for the 2016 individual membership election for the Node.js Foundation Board of Directors please comment here and link to a blog post about yourself and why you would like to represent the individual membership of the foundation.

Please make sure that you have registered as a member of the foundation prior to announcing your nomination (more information on how to do this will be public soon).

Relevant Links:
- https://nodejs.org/en/foundation/members/#becoming-an-individual-member
- https://nodejs.org/en/blog/community/individual-membership/

**Comment by guyellis** [comment]
[Guy Ellis answers why](http://www.guyellisrocks.com/2015/11/node-foundation-membership-election.html).

**Comment by mikeal** [comment]
BTW, this closes on January 15th so please get all nominations in by then :)

**Comment by Fishrock123** [comment]
~~Consider me as running if there is no one else willing to give some running competition.~~

Resigning mine since there are now 3 people running.

cc @nodejs/collaborators, if anyone is interested and didn't see this.

**Comment by ghost** [comment]
@mikeal are there any sort of other restrictions, such as age, location etc?

**Comment by mikeal** [comment]
> are there any sort of other restrictions, such as age, location etc?

Nope.

**Comment by Fishrock123** [comment]
You must be able to join in calls for the board meetings, I think. That would be about it.

**Comment by mikeal** [comment]
Relevant links: 
- https://nodejs.org/en/foundation/members/#becoming-an-individual-member
- https://nodejs.org/en/blog/community/individual-membership/

**Comment by MylesBorins** [comment]
@mikeal do you have any length requirements to the post?

**Comment by mikeal** [comment]
> do you have any length requirements to the post?

nope.

**Comment by ghost** [comment]
[here's me then](http://jona.io/blog/board-application/)

**Comment by Danese** [comment]
Mikeal,

Can we give them an idea of the time / travel commitments (if any) and a
brief description of what Board service entails?

<3 D

**Comment by mikeal** [comment]
@Danese is this enough? https://nodejs.org/en/blog/community/individual-membership/#what-does-the-board-of-directors-do

**Comment by Danese** [comment]
That's perfect!i knew you had something together ;-). A link to I t should go along with calls for nominees, is all I'm saying.

<3 D

**Comment by ashleygwilliams** [comment]
[hi my name is ashley hi](https://medium.com/@ag_dubs/hi-i-m-running-for-the-node-foundation-board-of-directors-c87d762cb78b#.gatiysgch)

**Comment by zeke** [comment]
@mikeal there's nothing in the issue title or body indicating that this is about "board of directors" membership. It wasn't really clear to me until I read the title of @ashleygwilliams's (awesome) post.

**Comment by mikeal** [comment]
@zeke updated description :)

**Comment by yocontra** [comment]
[🚨My information 🚨](http://contra.io/node_board.txt)

**Comment by 0zguner** [comment]
:+1:  @contra

**Comment by geek** [comment]
@mikeal [here is my information](http://jsgeek.com/posts/node-foundation-board-nomination.html)

@hueniverse thanks for the encouragement.

**Comment by joshmanders** [comment]
+1 for @contra and @ashleygwilliams I can't really decide 100%, so give it to both. Pack it in, this vote is over. Good job everyone. I expect to see you both ready and raring to go Monday morning bright and early.

**Comment by RamirezAlex** [comment]
@contra :+1:

**Comment by jbergstroem** [comment]
Guessing this will not be the place to vote, so can we please avoid that to keep noise down for now?

**Comment by jasnell** [comment]
Yes, please. This thread is for nominations _only_. While showing support for those stepping up is a good thing in general, this is not the right place to do so.

**Comment by jaredhanson** [comment]
[I'm running](http://jaredhanson.net/blog/2016/01/13/im-running-for-the-node-js-foundation-bod/).

**Comment by tejasmanohar** [comment]
I'm running. Read my application [here](https://medium.com/@tejasmanohar/node-js-foundation-board-of-directors-5514e8faa660).

**Comment by bnb** [comment]
I have decided to run - you can find my application [here](http://bnb.im/blog/Individual-Membership-on-the-Board-of-Directors-for-Node-js.html).

**Comment by watson** [comment]
:tada: [I hereby declare my candidacy for the mad science ticket](https://medium.com/@wa7son/why-i-m-running-for-the-node-js-foundation-board-of-directors-253bc2e3a834#.oarxi35e2) :smiley:

**Comment by feross** [comment]
I'm running for the Board of Directors. [My blog post is here.](http://feross.org/node-board/) :star2:

**Comment by pgte** [comment]
I'm running. [My application is here](https://gist.github.com/pgte/cfbf468202b35be78c66).

**Comment by ecowden** [comment]
I suppose I'll throw my hat in the ring. [Hello, World](https://medium.com/@evan.cowden/the-world-s-worst-resume-e0adf234baa0#.47ru4hped).

**Comment by mikeal** [comment]
Nominations are now closed :)

All current nominees are listed [here](https://github.com/nodejs/membership/blob/master/README.md#schedule). Let me know if I missed anyone :)

**Comment by tejasmanohar** [comment]
How many seats are available for the position?

**Comment by ashleygwilliams** [comment]
2, but members can only vote for one person.

**Comment by sam-github** [comment]
@mikeal how do I get the free-for-collaborators membership? Or anyone else know?

**Comment by r-52** [comment]
@sam-github there's an issue in the member repository with the instructions and link.

**Comment by guyellis** [comment]
Fantastic job running his election @mikeal 

I was super impressed with the number of high quality candidates and think that we have ended up with 2 great members for the roles. Congrats again to @ashleygwilliams and @feross

**Comment by zeke** [comment]
:tada:

**Comment by tejasmanohar** [comment]
:tada:

**Comment by thefourtheye** [comment]
Cross posting the result https://github.com/nodejs/membership#2016-election
