### ISSUE TITLE
Link to Node.JS Project Contributors Membership is 404

### ISSUE THREAD

**Issue by shama** [nodejs/board#14]
> Node.JS Project Contributors (any member of the GitHub Org): free

https://github.com/nodejs/members/issues/1 looks like it no longer exists or is private. What is the process for contributors to register now?

Thanks!

**Comment by ashleygwilliams** [comment]
hi! if you aren't able to see that link it means that you are not a "contributor member". if that is in error-- you should ping @mikeal.

otherwise, an individual membership is $100, student $25, as mentioned in the `README`

hope this helps!

**Comment by ashleygwilliams** [comment]
in fact, i think i'll add something to that to clarify. good catch! thanks for filing!

**Comment by joshmanders** [comment]
Hmmm, I am a paying member, but I cannot see that issue. I have changed my github name from what it was when I registered, does that make a difference? ping @mikeal

**Comment by ashleygwilliams** [comment]
ah @joshmanders -- that link is a private repo for people who are contributors to an Official Node.js Working Group or Repository, they belong to a Members team in the nodejs Github org

**Comment by joshmanders** [comment]
Oh okay, I thought it was for individual memberships too. That make sense. Thanks @ashleygwilliams

**Comment by shama** [comment]
Ah ok. Maybe @mikeal hasn't finished adding prior contributors? https://github.com/nodejs/node/issues/3802#issuecomment-169841101

I have 23 commits on node. Does that qualify for a free individual membership?

**Comment by ashleygwilliams** [comment]
clarifying PR here: https://github.com/nodejs/membership/pull/15
feedback welcome :smile:

**Comment by shama** [comment]
Fixed by #15
