### ISSUE TITLE
I'm not a member even though I participate in a Working Group

### ISSUE THREAD

**Issue by watson** [nodejs/board#17]
I'm a member of the [Node.js Tracing Working Group](https://github.com/nodejs/tracing-wg) and as far as I can understand from the [Cost section](https://github.com/nodejs/membership/blob/master/README.md#cost) I should therefore be on the [Members team](https://github.com/orgs/nodejs/teams/members) on the [Node.js GitHub organization](https://github.com/nodejs), but since I get a 404 when accessing it I guess that I'm not?

**Comment by mikeal** [comment]
Whoever is managing that WG didn't invite/add you to the Tracing team in the org. I've fixed that, once you accept the invite check out the issue tracker in the "members" repo for the discount code.
