### ISSUE TITLE
Q&A w/ @contra on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#22]
This thread is for asking @contra questions regarding [his run](http://contra.io/node_board.txt) 
for the Node.js Foundation Board of Directors.

**Comment by rosskukulinski** [comment]
Hi @contra!  Thanks for applying to be an Individual Member.  I read your application which primarily focuses on your past/ongoing contributions as a NodeJS developer.  I'm hoping you could expand more on what you hope to accomplish as an individual member of the NodeJS Board and where you hope to see Node go in the next 3-24 months.

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by yocontra** [comment]
@rosskukulinski

My first concern (primarily because of gulp) is fixing node's stream implementation and adding functionality the community has been requesting for a long time. This includes finding a point of convergence between the browser Stream implementation and what we use in node.

After that, I'd like to see a renewed focus on documentation and discoverability in the ecosystem to curb module fatigue and let quality/maintained modules float to the top.

**Comment by lmarkus** [comment]
@contra wouldn't the first point be better served by joining the TSC?

As a potential representative of the community, what non-technical issues do you see today that you'd bring to the board?

**Comment by rvagg** [comment]
thanks for nominating @contra!

<strike>I'd like to know what pop song(s) best represents your desires for the Node.js Foundation. _Answers are also acceptable in interpretive dance form._</strike>

Question retracted, likely to be too controversial and potentially unfair to other nominees if interpretive dance gets involved.

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
