### ISSUE TITLE
Q&A w/ @jaredhanson on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#24]
This thread is for asking @jaredhanson questions regarding [his run](http://jaredhanson.net/blog/2016/01/13/im-running-for-the-node-js-foundation-bod/) 
for the Node.js Foundation Board of Directors.

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by rosskukulinski** [comment]
Hi @jaredhanson!  Thanks for applying to the board.  I read your application and I was hoping you could expand more on this statement:

> As a member of the Board of Directors, I want to help continue and accelerate this success and growth.

Specifically, what do you think the Node ecosystem (via the Board) should do to continue its successful growth?  What are the priorities and how do you think we can accomplish them?

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by jaredhanson** [comment]
> (A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

I would list the three most important issues as follows:
1. Platform Stabilization
2. Ecosystem Support
3. Community Development

These issues are somewhat inter-related, so I'll expand on my view.

**Platform Stabilization**

I think one of the drivers of Node's success to date has been that it found a sweet spot in terms of simplicity and ease-of-use, while still allowing for sophisticated development.  A large part of this is the choice of JavaScript as a language, and the use of V8 as a stable runtime.  The other big component is the focused nature of the core modules and the extensibility offered by deferring other functionality to external modules, with an assist by npm.

Maintaining that balance, while not stalling continued evolution or succumbing to complexity is crucial for the platform.  This is, of course, the responsibility of the Technical Steering Committee (which is doing a great job), but the board should reinforce it as a priority, which can be done by addressing the other two issues.

**Ecosystem Support**

Ecosystem support, done effectively, can help drive both platform stabilization and evolvability.

In terms of evolvability, non-core modules are one of Node's biggest strength.  I think Node should harness that for experimental features wherever possible.  For example, newer asynchronous code patterns could be prototyped (or fully implemented) outside of Node core, allowing for faster iteration while lowering risks to stability.

This does beg the question about Node core and its relation to package managers (and npm specifically).  Having a community-led platform, with a corporate-run package manager, will be one of the most sensitive issues Node wrestles with in the coming months.

Much of this will involve discussions with npm, Inc., but I believe the third-party module ecosystem is crucial to Node's continued growth, and therefore its important to have a package distribution system that operates in the interest of that community (be it corporate or individual).

Also on the ecosystem support front, tooling to assist with operating applications at-scale is important.  We are making great strides here, especially with contributions from those companies with the largest deployments.  We should continue with these efforts.

**Community Development**

The community is what is ultimately responsible for Node's success, and the ecosystem that has built up around it.

That community arises directly as a result of the simplicity of Node itself, and the vast number of people (of all skill levels), who are familiar with JavaScript and can easily make contributions by publishing modules, writing documentation, etc.

We should continue to grow the community, making it easy for new developers to adopt Node and navigate the wider ecosystem.  Again, I think maintaining the relative simplicity of Node core makes the job of educating new developers easier.  I also think there's an opportunity for the Node.js Foundation to help navigate the broader ecosystem.  This is where I'd like to see more involvement with people who develop modules outside of Node core.

> (B) In a single sentence, how would you describe the role of the person elected to the board?

To listen to, and understand, the needs of individuals using Node.js, and then find ways to address those needs while working with the other board members.

**Comment by jaredhanson** [comment]
> Specifically, what do you think the Node ecosystem (via the Board) should do to continue its successful growth? What are the priorities and how do you think we can accomplish them?

@rosskukulinski I'll refer you to my above answer, which goes into detail on what I see as the priorities for the Node.js Foundation.

I'd also note that the Node ecosystem has brought about this success, and the creation of the Foundation is a relatively new development in Node's evolution.  In determining the priorities, and how they are accomplished, I think its important for the Foundation to recognize the key drivers that have existed in the wider ecosystem itself, and ensure that those factors are preserved while still growing to meet the needs of a "mature" development platform.

**Comment by jaredhanson** [comment]
> 1. What do you see as the most significant obstacle to node.js's continued growth?

Stabilizing as a "mature" development platform, while not limiting the pace by which the ecosystem evolves.

> 1. What do you think the node.js foundation can do to address your answer to #1?
1. Maintain the focused nature of Node core, and further develop tooling to help with debugging, optimization, etc.
2. Expand efforts outside of Node core.  This can come in a wide variety of forms, including support for existing modules or providing community-run mirrors for package distribution.

**Comment by dscape** [comment]
Jared you have a great ideas, I was just browsing through and must say excellent responses. Lots of the focus are things that I've seen people struggle with, you can easily see you work a lot with node production.

Having people like you apply really validates all the effort @mikeal is putting on this effort and community inclusion. So thank you for this.

**Comment by rvagg** [comment]
thanks for these answers @jaredhanson, great to have you running, it's obvious that you've put a lot of thought into these issues.

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
