### ISSUE TITLE
Q&A w/ @bnb on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#26]
This thread is for asking @bnb questions regarding [his run](http://bnb.im/blog/Individual-Membership-on-the-Board-of-Directors-for-Node-js.html) 
for the Node.js Foundation Board of Directors.

**Comment by bnb** [comment]
Hey everybody! Ask away, willing to answer any and all questions.

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by rosskukulinski** [comment]
Hi @bnb!  Thanks for applying to be an individual member of the board.  I'm wondering if you could explain if/how your experience as a current student differentiates you from most of the other candidates.  

In addition, how do you plan to engage with the large (and growing) NodeJS community and channel that back to the Board?

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by bnb** [comment]
@jasnell 

> A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?
- Starting initiatives to begin supporting, encouraging, and assisting the Node community in building open learning tools, relationships and communities that allow _anyone_ interested to become a working Node developer. The issue for me is that there is a knowledge gap that is _hard_ to cross without specific resources available, and I want to ensure that the community is actively working to provide the most accessible, friendly, and understandable resources to help find a resolution for this.
- Creating opportunities for those who are a part of a minority, who are remote, or who couldn't normally access available communities. I would go about this via rallying the Foundation-led events, via new, unconventional mediums (media is plural of medium, but mediums conveys the message I'm trying to convey more clearly). Basically, inclusivity for learning Node, for both commonly known under represented groups as well as those that are less clearly defined. 
- Encouraging, finding, and developing resources (such as Node modules, community members, initiatives, innovative groups and companies, and so on) that will further the saturation of Node in the overall developer community, including that outside of Node's. I really believe that Node is the strongest platform for building developer tools that currently exists - I have a very strong interest in this topic, and I would like to do whatever I can within the Foundation to help guide and grow the developer tool ecosystem via supporting the developers who are innovating in this area.

> (B) In a single sentence, how would you describe the role of the person elected to the board?

The person who is elected to the board is a representative of the individual members of the Foundation who needs to represent their best interests in deciding on Node's legal discussions, finding the appropriate budgeting solutions, and creating, supporting, and maintaining Foundation-led events and initiatives.

**Comment by bnb** [comment]
@rosskukulinski 

> explain if/how your experience as a current student differentiates you from most of the other candidates. 

My experience as a student does differentiate me from most of the other candidates. I've attended and graduated a community college to get credentials for a longer, better BA/MA program. I'm quite amazed at the people I've met in my programs. 

I've always talked about the web and Node with them, and I've gained a lot of insight into what both academics and students think, feel, and know about these topics. The overwhelming majority are interested in programming, the web, and the unique properties that Node has to offer. I have a strong understanding of what these two groups do and don't understand, and what could or could not be done to bring Node to them in a way that they can understand and adopt.

Understanding this gives me insight into how the vast majority of educated people understand Node and its various surface-level concepts. I can apply this knowledge to help develop initiatives, create Foundation-led conferences, and other programs that will allow us to convert these people into contributing community members.

**Comment by bnb** [comment]
@jden

> 1: What do you see as the most significant obstacle to node.js's continued growth?

I'd say the biggest obstacle is something that I've seen hit project after project: maintaining at scale. Huge projects often fall over under their own weight. Node seems to me to be on the path to being the biggest programming (platform || language || library || xyz) in the market today and in the near future. The distant future is what I'm worried about, and it's what we need to work to ensure Node's growth in.

> 2: What do you think the node.js foundation can do to address your answer to #1?

The opposite of what other megalithic programming projects have done. What is that? There are many things to list here, which could themselves go into a megalithic blog post. Chunking that up, studying, and implementing counter measures - the opposite of what had been done in the past - would be an ongoing initiative that I would be happy to start, implement, and maintain under the Foundation. 

The number one obstacle for me, though, is staying lean. I know many large projects have died to over-development and bloat - one of the best things to help the community avoid this would be to create guidelines, definitions, and boundaries on what Node is, what it does, and what it needs. 

There are many, many people who I strongly believe in and I am fairly confident (though I don't want to assign beliefs or values to them) that they would fight hard and long to get Node to where it needs to be to survive - io.js is the prime example of this. I was a small part in that, and I know just how dedicated and amazing the Node community is when it comes to believing in Node being the best it can be. These people are the ones that would be able to help create this structure. They are the generation that will be defining Node for the next several generations, so we should embrace that and bring them closer to the project.

**Comment by bnb** [comment]
Forgot to mention commenters in answers - edited, and linked below. 

@jasnell - https://github.com/nodejs/membership/issues/26#issuecomment-172626062
@rosskukulinski - https://github.com/nodejs/membership/issues/26#issuecomment-172655980
@jden - https://github.com/nodejs/membership/issues/26#issuecomment-173393629

**Comment by rvagg** [comment]
hey @bnb, thanks for nominating and taking the time to answer in detail.

**Comment by bnb** [comment]
@rvagg no problem! Answering the questions, having to be introspective, was very self-enlightening about my ideas and thoughts behind Node and my involvement with it.

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
