### ISSUE TITLE
Q&A w/ @ecowden on Individual Membership Candidacy

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#30]
This thread is for asking @ecowden questions regarding [his run](https://medium.com/@evan.cowden/the-world-s-worst-resume-e0adf234baa0#.47ru4hped) 
for the Node.js Foundation Board of Directors.

**Comment by jasnell** [comment]
(A) If elected, what do you envision would be three most important issues that need to be addressed and how would you go about advocating for / resolving those?

(B) In a single sentence, how would you describe the role of the person elected to the board?

**Comment by rosskukulinski** [comment]
Hi @ecowden!  Thanks for applying.  I read your application I've got a comment/question for you:

The current board already has considerable membership from enterprise companies, so how do you feel your input will be different from theirs?  Do you plan on listening to the non-enterprise community?  If so, how do you think you might do that?

**Comment by junosuarez** [comment]
1. What do you see as the most significant obstacle to node.js's continued growth?
2. What do you think the node.js foundation can do to address your answer to #1?

**Comment by ecowden** [comment]
Great questions @jasnell and @rosskukulinski! That first one deserves a more elaborate answer, but I want to tackle Ross's right now.

I went back and forth about whether to toss my hat in the ring right up to the last minute, and that's one of the big questions that was hanging on my mind. Ultimately, I think there are two things that put me in a different position than existing corporate board members.

First, I work at a company that feels very, very different than the others. When you look at Microsoft, IBM, or Red Hat...those are by and large software companies. They _do_ software. Even companies like PayPal and GoDaddy.com feel similar. They may not sell software like Microsoft, but the bulk of their business is driven by their web presence and software engineering. Unlike them, we _use_ software to help our employees or partners, but at least in the internal IT organization where I spend my days, we're not a software company.

Second, _I am not representing my employer._ I am _not_ running as a corporate member, and I haven't even told anyone at the office that I'm a candidate. I'm here first and foremost as a developer -- not a company. I want to represent myself, my coworkers and others in similar situations. 

I know a lot of people who enjoy working with Node.js, people who get excited about working with Node.js. We may use it for personal projects, but using it at the office takes a different kind of thought. These are environments where technology choices shift slowly and deliberately, and need to take into consideration a lot more constituencies than a team of developers. Places where adopting something like Node.js takes a great deal of perseverance, an ability to consider concerns from many different parts of the organization, and a willingness to engage in an open dialog with everyone from development and operations through management and leadership.

Now, again: I don't think this is a _bad_ thing, and I hope I'm not painting a dreary picture of living under the thumb of ignorant corporate overlords. We had to figure out _real_ concerns, from deployment and disaster recovery through accessibility, hiring, training and cross-training. Things like, how will "new" software work with "old" software? Does this align with what we want to do for our users? How can we invest time in a new technology while meeting existing commitments?

That leads me to the second half of your question, Ross: would I listen to the rest of the Node.js community? Yes, I would absolutely listen to everyone. At the end of the day, I hope to have one community, not a fragmented collection of sub-communities. I remember way back to my old high-school debate coach telling us how communications would be the most important skills we'd use on the job. At the time, I thought she meant public speaking. Now I realize that it's a two-way street, that listening is just as important as talking. Please forgive my temporary lack of humility, but I've spent a lot of time listening, explaining, debating, cajoling, compromising and collaborating lately. That's what I want to continue to do, and that's the experience I want to bring as a member of the board.

All that said: if you don't feel like I'm what the community needs, or if you don't think I have the right background, then please vote for someone else! We're fortunate to have plenty of great candidates, many of them with much better open-source and community credentials than me. I'm in the lucky situation knowing that even if I lose, I'm going to be happy with the winner!

**Comment by rosskukulinski** [comment]
Thank you, kindly, @ecowden for your thoughtful response.

**Comment by rvagg** [comment]
Thanks for your answers @ecowden, and thanks for nominating!

**Comment by mikeal** [comment]
Election is over, results are [posted](https://github.com/nodejs/membership/blob/master/README.md#2016-election).
