### ISSUE TITLE
Can't join with GitHub due to existing Linux Foundation account

### ISSUE THREAD

**Issue by watson** [nodejs/board#31]
The README.md tells me to join with my GitHub account, but I already have a Linux Foundation account so when I try to log in using GitHub, I'm told another account already exists with those credentials. I couldn't find a way to associate my GitHub account with my existing account.

**Comment by mikeal** [comment]
Can you send an email to helpdesk@rt.linuxfoundation.org

**Comment by watson** [comment]
They responded with an easy solution, that we might want to share for others who have the same issue (basically most people who attended Node Interactive and got a Linux Foundation account as a result).
1. You first log into your existing Linux Foundation account
2. Then you visit https://identity.linuxfoundation.org/user/me/hybridauth and authorize GitHub
3. Finally you visit https://identity.linuxfoundation.org/pid/99 to register for membership of the Node.js Foundation
