### ISSUE TITLE
Foundation member label on Github?

### ISSUE THREAD

**Issue by joshmanders** [nodejs/board#35]
![](http://i.imgur.com/HgBke78.png)

Just noticed these. Do all members get them?

**Comment by mikeal** [comment]
where is that in the UI?

**Comment by mikeal** [comment]
That's probably just a label all org members get in issues in the org?

**Comment by joshmanders** [comment]
Top of post, yours has it right now.

https://www.dropbox.com/s/8getm3nyi0ycdbt/Screenshot%202016-02-05%2011.21.42.png?dl=0&preview=Screenshot+2016-02-05+11.21.42.png

**Comment by mikeal** [comment]
Ya, that's an org membership thing.

**Comment by joshmanders** [comment]
Oh must be new rollout, I hadn't seen it anywhere but on Node issues and it just all of the sudden showed up.

**Comment by mikeal** [comment]
I got a few other emails today about small changes related to GitHub orgs so I think there was a push last night or this morning with this stuff.

**Comment by joshmanders** [comment]
Awesome, thanks for responding, I'll let you get back to more important things.

**Comment by Fishrock123** [comment]
I just removed the "The" in the org name so that it reads better.

**Comment by mikeal** [comment]
> I just removed the "The" in the org name so that it reads better.

good call :)

**Comment by mikeal** [comment]
Haha, caching :) 

<img width="783" alt="screen shot 2016-02-05 at 9 28 05 am" src="https://cloud.githubusercontent.com/assets/579/12853789/cee545c2-cbea-11e5-92cf-e875090df412.png">

**Comment by MylesBorins** [comment]
This work?

**Comment by joshmanders** [comment]
Looks like it.

**Comment by MylesBorins** [comment]
@mikeal I just noticed that this new label is trumping Collaborator and Owner in the main repo. Is that the intended result?

**Comment by mikeal** [comment]
@TheAlphaNerd I have no idea, but that is quite odd and pretty problematic. I don't think there is anything we can do about it though.

**Comment by Fishrock123** [comment]
@mikeal / @TheAlphaNerd did you report to GitHub support?
