### ISSUE TITLE
List of members?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/board#36]
Is there a list of people that are members?
Maybe just a running total of how many members strong we are?

**Comment by cdnadmin** [comment]
@williamkapke if you look at the **Cost** [section](https://github.com/nodejs/membership#cost) of the README file, you'll see a link ([Members team](https://github.com/orgs/nodejs/teams/members)), in the asterisk/footnote, to what appears to be a members list.  But, it's a private repo--like the asterisk/footnote indicates.  You'll get a 404 if you don't have access--understandably.

I'm hoping that @mikeal or @ashleygwilliams (or anyone with access) can dup that list in here, for those of us that are non-members (for now 😉 ) to see the list, per your point above.  

Btw, I'm thinking you already knew what I mentioned in the first paragraph, but I wanted to comment to "ping" others.  😉

**Comment by williamkapke** [comment]
@cdnadmin this is a big point of confusion for many people. The list of GitHub users in the Members team are just the ones eligible for free membership to The Node.js Foundation. Being a member of _The Node.js Foundation_, by paying the fee, makes you a member of the legal entity as defined by the [Certificate of Incorporation](http://f.cl.ly/items/2b1b1o0v1e1u2i1L2w1a/nodejs-foundation-certificate-of-incorporation-2014-august-01.pdf) and [By-Laws](https://nodejs.org/static/documents/node-foundation-by-laws.pdf).

This issue was created before I knew of the confusion- thanks for pinging it. So, to clarify, I was asking for the list of **Members of the corporation**. I ask because I would like to know the reach of people participating in electing Individual Members to the Board and it seems like candidates should be allowed to know who their constituency is.

It sounds like you're interested in knowing the numbers about members of the GitHub org maybe? **Publicly** listed on GitHub there are 236 members right now. But as member of the org (but oddly not a member of 'Members') I can see there are over 400. A few public talks are out there that reference the 400 number too.

Note: Not everyone chooses to publicly list being a member of the GitHub org. Actually I get the idea that the default is to NOT show it until you go change the setting.

**Comment by mikeal** [comment]
So, we never asked for permission to publish their association when they signed up to be a member so we would need to do some kind of secondary step, similar to GitHub, in order to do that.

**Comment by williamkapke** [comment]
How about offering a free "Member" hat/tshirt the new Node.js store!
<sup>†† with `permission to publish` agreement</sup>

Just kidding ;)

**Comment by williamkapke** [comment]
@mikeal can we ask for their permission this time around?

**Comment by williamkapke** [comment]
Bump

**Comment by williamkapke** [comment]
Welp- I can take on this task myself now. Closing.
