### ISSUE TITLE
Foundation Board Code of Conduct?

### ISSUE THREAD

**Issue by joshmanders** [nodejs/board#37]
I've looked at the [Node.js Project Code of Conduct](https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md) and I'm not sure if that applies to just the project or the whole of Node.js Foundation. Is there a specific Code of Conduct for board members? Especially in how they conduct themselves in public places in regards to members of the foundation?

**Comment by jasnell** [comment]
That's a good question but it's out of the jurisdiction of the TSC. We can raise it as a concern and if there are specific incidents of concern, you can post the details either to the moderation repo if you're comfortable with that, or private message the TSC members (or individual members) and we can follow up.

**Comment by mikeal** [comment]
Unless someone explicitly states they are representing the foundation, they are not representing the foundation.

Unless someone explicitly states they are representing the board of directors, they are not representing the board of directors.

The conduct of a member of the board when they are not representing the foundation or the board is not an issue for the Node.js Foundation or the Board of Directors.

It is also not appropriate to post issues against someone's affiliations when you disagree with them or their conduct as it is a form of harassment. 

I will work on some clear messaging for the website that notes that affiliates of the foundation do not represent the foundation. I may also work on a document for board members to reference when they _do_ represent the foundation but that is incredibly rare and we've never had a problem in that particular case.

**Comment by joshmanders** [comment]
So community elected board members are not affiliated with the foundation? I'm confused at what you're stating.

**Comment by mikeal** [comment]
The don't _represent_ the foundation except when specifically tapped by the foundation to act as a representative. For instance, when we do big announcements we usually have a few people act as representatives to the press. There are also cases where I interview people or work to create other content for the foundation and act as a representative myself.

The foundation cannot, and should not, attempt to take responsibility for or dictate the behavior of individuals affiliated with the foundation outside of the work they do specifically in their role within the foundation.

**Comment by jasnell** [comment]
For example,

If the board member is clearly acting on behalf of their employer and in a
role assigned to them by their employer, the foundation has no oversight
unless there is a clear conflict of interest or direct impact on that
individuals ability to adequately fulfill their fiduciary responsibility to
the board and to the membership.

**Comment by mikeal** [comment]
> If the board member is clearly acting on behalf of their employer and in a
> role assigned to them by their employer, the foundation has no oversight
> unless there is a clear conflict of interest or direct impact on that
> individuals ability to adequately fulfill their fiduciary responsibility to
> the board and to the membership.

This is a tricky one. Some people involved with the foundation actually _do_ represent their employer in their role in the foundation. The elected at-large board members represent a class and if an issue was a conflict of interest between their employer and the class they represent they would likely just abstain from participating in that specific topic/work.

**Comment by joshmanders** [comment]
Okay, I get it now, thank you for clearing that up.
