### ISSUE TITLE
Nominations for 2017 Individual Member representative

### ISSUE THREAD

**Issue by williamkapke** [nodejs/board#38]
Almost 1 year ago- nominations opened up for the Individual Membership representative. So- it seems we should be due to start the process again.

My research says @feross's term will be ending in January.

**Comment by mikeal** [comment]
Correct.

We should also use the nomination process to encourage and promote individual membership in the foundation leading up to the next election.

It would also be cool if we could get candidates to do a few podcasts and other media about why they want to run. I bet NodeUp would be excited about that.

**Comment by williamkapke** [comment]
How about a section at Collaborator Summit US?

**Comment by mikeal** [comment]
@williamkapke I like the idea but I'm a little worried about advantaging people running who attend vs. those who can't make it.

**Comment by hackygolucky** [comment]
@williamkapke I love the idea of introducing this at NI NA. It's a great way to kick off the nomination season. I think @mikeal has a good point that we should resist the urge to make it appear that one has to be attending(so we need to have lots of outreach outside of this) in order for nominations to occur. 

We have such a global reach, it would be unfortunate for people the world over to think that since they couldn't attend the North American event that they don't have a place to run.

**Comment by williamkapke** [comment]
FWIW, I think all options (even NodeUp) have the possibility of being exclusive.

**Comment by MylesBorins** [comment]
what are the time lines we are considering for the election this year?

**Comment by mikeal** [comment]
Same time every year, so voting and election in January around the same time as last year.

**Comment by jasnell** [comment]
Thank you @williamkapke for opening this... while I definitely do not want to se @feross' term come to an end, it's good that we've got this rolling early.

**Comment by jasnell** [comment]
@mikeal ... can you please refresh memories on the nomination process?

**Comment by hackygolucky** [comment]
We were planning on opening up nominations and making sure documentation
around what it means to lead as a director at Node Interactive NA. Giving
about a month before the election will be helpful to making sure people
know what they are signing up for to set them up for success.

**Comment by hackygolucky** [comment]
Nominations open now and [HERE](https://github.com/nodejs/membership/issues/40)!
