### ISSUE TITLE
Open nominations for Individual Membership Director for the Node.js Foundation Board

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/board#40]
### The 2017 nomination for the Individual Membership Director seat is now ~~open~~ closed. 

Nominations are being solicited until January 15th.
A ballot will be distributed on January 20th.
The election will be completed by January 30th.

UPDATE
We'll be share the link for voting on Friday, January 20th.  Voting will close on January 30th at **17:00 UTC**. Nominees will be notified same day and prior to the January Node.js Foundation Board meeting.

Please comment here and link to a blog post about yourself and why you would like to represent the individual membership of the Foundation. We will be providing further content that will help inform folks on what is means to be a Director soon!

Please make sure that you have [registered as a member](https://nodejs.org/en/blog/community/individual-membership/) of the Foundation prior to announcing your nomination.

Relevant Links:

https://nodejs.org/en/foundation/members/#becoming-an-individual-member
https://nodejs.org/en/blog/community/individual-membership/

### Nominations: 
(Please update!)
- Your name here! @yourgithubhandle
- William Kapke @williamkapke 
- Charlie Robbins @indexzero 
- Kat Marchán @zkat 
- William P. Riley-Land @wprl

**Comment by bnoordhuis** [comment]
Tangential: I'd be interested in a retrospective from this year's board members on their experiences and what they managed to accomplish.  Might be useful as a starting point for candidates.

**Comment by williamkapke** [comment]
At Node Interactive I was encouraged by several people to run for the position. I assumed @feross would rerun, so I never considered the idea. He is a great person with a significant voice in the community.

<del>There hasn't been any indication from him that he will rerun however.</del>
<sup>UPDATE: He said he isn't running below.</sup>

**I would really enjoy representing the community as an Individual Member Director** and it would help **accelerate the community efforts I've been working on** the past year!

To learn _more_ about who I am, what I've done and details on why I'm running..
**CHECK OUT MY VIDEO BELOW!**

[![I'm running for the Node.js Board of Directors!](https://cloud.githubusercontent.com/assets/739813/21962043/5bb2af1e-dacf-11e6-9b33-0df33f2d37b9.png)](https://youtu.be/zPBOkqclJFc)

**Comment by rosskukulinski** [comment]
Building off of @bnoordhuis, I would also be interested in learning more about the expectations (e.g. time commitment, travel, engagement).  How has the role of Individual Member Director changed since its inception last year and what is the board hoping to accomplish in the coming year?

**Comment by hackygolucky** [comment]
@bnoordhuis @rosskukulinski  Three Directors-- @indexzero, @feross and @ashleygwilliams will be releasing a post on what it means to be a director, and specifically what an Individual Membership director will need to do in order to be successful in the position soonish. It is especially important for everyone to know what expectations they'll need to manage, as being a Director on a Board takes a set of skills and an interest in things that most folks would not enjoy but are important to getting things done--so thanks for asking for this!

**Comment by feross** [comment]
@williamkapke I'm not planning to run for a board seat again, so by all means go for it!

**Comment by thepotusdonaldtrump** [comment]
Thiel mentioned this at our tech meeting today. He thinks I could help bigly. Let's make NodeJS great again.

**Comment by jfathman** [comment]
@williamkapke After hearing your talks at Node Interactive, I think you would bring communication, transparency, accountability, reporting, and new right-sized process to the Node Foundation.  I hope you run for the position.  Thanks for stepping up.

**Comment by indexzero** [comment]
> ### _A longer [Statement of Interest](https://gist.github.com/indexzero/5b17885d8f8044b674a1fa411e1f7e3b) and [Full Bio](https://gist.github.com/indexzero/5b17885d8f8044b674a1fa411e1f7e3b#about-charlie) can be found [here](https://gist.github.com/indexzero/5b17885d8f8044b674a1fa411e1f7e3b)._

For the last 18-months I have served on the Board of Directors on behalf of the Gold members who elected me in 2015. This past year, the Gold membership tier shrank by one to only two members. The Node.js foundation by-laws state that:

> "In the event that there are two Gold Members, each desiring to vote for its own nominee, the winner **shall be determined by a coin toss."**

I lost that coin toss this December and as a result will cease to be on the Board of Directors as of January 2017. I've been part of the Node.js community for a long time. I feel that I've been able to help it continue to grow & improve it as a member of the Board. To further this goal of continuing to support the Node.js community through a Board seat I am running for the Individual Seat on the Node.js Foundation Board of Directors. Please accept my deepest thanks for your consideration to vote for me on the Board in the upcoming election.

**Comment by zkat** [comment]
After some conversations with folks who encouraged me to do this, I'm putting in my nomination for **Individual Membership Director** [(click for more detailed statement of interest)](https://gist.github.com/zkat/345d1485fc4cd1f45155678a3729cd21) . 🙌 

I think there's a lot of good work to be done here, even taking into account the boundaries between the Board and Node Core. I've been really frustrated in the past with how hard it was to push things forward, with those already in place being unable or unwilling to take action to change things for the better -- or even actively opposing our efforts. 😞 

I want to try again, with something a little different. I hope you'll consider me for this position, and I have every intention of making it my priority to advocate and represent the wider Node community that has relatively little say in the Board compared to corporate-sponsored positions that make up its majority. I will be there for *you*. 😘

**Comment by bnoordhuis** [comment]
> I've been really frustrated in the past with how hard it was to push things forward, with those already in place being unable or unwilling to take action to change things for the better -- or even actively opposing our efforts.

That sounds both accusatory and vague.  It's not clear what "our efforts" are, or even who "our" refers to.

**Comment by Fishrock123** [comment]
> Three Directors-- @indexzero, @feross and @ashleygwilliams will be releasing a post on what it means to be a director, and specifically what an Individual Membership director will need to do in order to be successful in the position soonish.

@hackygolucky did this ever get posted? It is very important and I do not see it anywhere.

**Comment by hackygolucky** [comment]
@Fishrock123 We released [the post a few places](https://hackernoon.com/whats-it-like-being-on-the-node-js-foundation-board-of-directors-f9456b8b7c4d#.7dfgw1z77), and it's being shared as much as we can help. More shares would be great!

Todd Moore(Board member) was kind enough to take the time to share his thoughts on this. We've been trying to coordinate this post since December, but everyone was really swamped. @indexzero also abstained from this post due to his current nomination in the election.

**Comment by zkat** [comment]
@bnoordhuis hi Ben!

By "our", I intended that to mean the Inclusivity WG that I was participating in at the time, as well as connected groupings of community members that may not have been working directly under that WG at the time or since -- groups of which I was a member myself. I hope that clarifies that part a bit.

I hear that you feel this was an accusation, possibly even directed at you. My intention was to make a simple statement of what I consider to be a fairly uncontroversial fact (I think a values conversation is orthogonal to its truthiness, since opposing things you don't like still means you're opposing them). What makes you feel that was an attack? Is it necessary to relitigate and go into detail about the history behind this stuff? Personally, I would rather not -- I'm looking ahead and I hope to find positive ways to make stuff better, with project-wide buy-in. That does include you. And I hope you'll give me a chance, too.

**Comment by bnoordhuis** [comment]
I didn't think it was a personal attack, don't worry.  I was mystified by the "us vs. them" undertone.

**Comment by ghost** [comment]
I would like to throw my hat in: https://medium.com/@wprl/i-would-like-to-represent-individual-members-of-the-node-js-foundation-977157d90aa0

**Comment by hackygolucky** [comment]
Closing this issue, as nominations are now closed. Very excited for all of our candidates! 

We'll be sharing the link for voting on Friday, January 20th.  Voting will close on January 30th at 17:00 UTC. Nominees will be notified same day and prior to the January Node.js Foundation Board meeting.

**Comment by gibfahn** [comment]
Posting the link to vote as I struggled to find it: https://nodejs.org/en/blog/community/2017-election/
