### ISSUE TITLE
2017 Node.js Foundation Individual Membership Director ballot now open

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/board#42]
## Ballot now open for voting through *January 30* at *17:00 UTC*.

The Node.js Foundation is a member-supported organization. The Node.js Foundation Individual Director is the Node.js project’s community voice on the board. There are two individual directors that sit on the Node.js Foundation board and they serve a two-year term.

The Individual Membership Director is responsible for soliciting feedback and data that represents the wishes of other individual members and the community at large. They have been entrusted with the duty to make decisions based on the information they receive to best represent the community, and can gather input for proposals when relevant and granted permission to do so.

This includes participating and voting in Board meetings, introducing and driving forward initiatives to conclusion that capture the mission of the Node.js project, and representing the Board at speaking engagements (this is by no means a comprehensive list). Read more about [“What’s it like being on the
Node.js Foundation Board of Directors?”](https://medium.com/@nodejs/whats-it-like-being-on-the-node-js-foundation-board-of-directors-f9456b8b7c4d).

### What does the Board of Directors do?
The Board meets every month to approve resolutions and discuss Node.js Foundation administrative matters. This includes legal considerations, budgeting and approving Foundation-led conferences and other initiatives. Technical governance is overseen by the TSC, not the Board of Directors.

The current board members are listed [here](https://nodejs.org/en/foundation/board).

### Who is running for the Individual Membership Director seat?
Read more about why our candidates are running below.

- William Kapke [@williamkapke](https://github.com/williamkapke)
  - [I'm running for the Node.js Board of Directors!](https://www.youtube.com/watch?v=zPBOkqclJFc&feature=youtu.be)
- Kat Marchán [@zkat](https://github.com/zkat)
  - [Director nomination for Kat Marchán](https://gist.github.com/zkat/345d1485fc4cd1f45155678a3729cd21)
- Charlie Robbins [@indexzero](https://github.com/indexzero)
  - [I'm running to increase transparency to the community from the Node.js Board
  of Directors](https://gist.github.com/indexzero/5b17885d8f8044b674a1fa411e1f7e3b)
- William P. Riley-Land [@wprl](https://github.com/wprl)
  - [I Would Like to Represent Individual Members of the Node.js Foundation](https://medium.com/@wprl/i-would-like-to-represent-individual-members-of-the-node-js-foundation-977157d90aa0#.hq3vo8d8m)

### When is the election? Nominations were solicited until January 15th.
- Ballot will be distributed on January 20th.
- The election will close **January 30th at 17:00 UTC**.  

# How do I vote?
You must be an Individual Member of the Node.js Foundation to cast a vote. If
you are a member, you can vote [NOW](https://vote.linuxfoundation.org)!

### How do I become a member?
Individual membership costs [$100 a year, or $25 for students](https://identity.linuxfoundation.org/pid/99).

Contributors to the Node.js project, including all Working Groups and
sub-projects, are eligible for free membership. Please
[contact us](mailto:membership@linuxfoundation.org) for discount codes. You are
required to have a GitHub account to register.

### What’s the benefit of being an individual member?
 - You have a vote and voice on the Node.js Foundation Board of Directors
 through the two above-mentioned elected Individual Membership Directors.
 - 20% off regular price registration to Node Interactive 2017

See you at the (digital)poll?

cc @nodejs/tsc @nodejs/ctc @nodejs/evangelism

**Comment by addaleax** [comment]
We should log in using github, right? I receive a warm “You are *not eligible* to vote in this election.” when doing that. (edit: if this is the wrong place to bring this up – where is the right one?)

**Comment by hackygolucky** [comment]
@addaleax did your membership expire? Will email you with the contributor code to see if that fixes things.

**Comment by bnoordhuis** [comment]
Are CTC/TSC members supposed to vote?  I figured we shouldn't because we already have representation on the board (at least, TSC members do, CTC members only indirectly.)

**Comment by hackygolucky** [comment]
@bnoordhuis If you're an individual member, you can and are welcome to vote regardless of whether you are also represented in voice by the TSC. I would say the question of who you vote for and the reasoning for what's important for an individual membership representative may be a bit more personal/subjective, but the directors(TSC rep, Individual Membership directors) have different audiences and, potentially then, priorities--they are representing. As a TSC/CTC/community member, you fall into multiple.

**Comment by nebrius** [comment]
I seem to recall last year that we had a digital Q&A for each candidate to answer questions from the community. Do we have plans to do so again this year (or did I simply miss that)?

**Comment by addaleax** [comment]
@hackygolucky yep, that did the trick. sorry!

**Comment by hackygolucky** [comment]
@nebrius I'd spent so much time trying to figure out ways for us to educate folks on -what- it means to be a Director and encouraging submissions from the global community that I didn't think about the individual platforms for the nominated candidates to get to answer questions from. We did not have plans to do that this time around, but I'm happy to set that up. Super quick. Thanks for the nudge!

**Comment by Trott** [comment]
I realize it's awfully late in the process to bring this up so maybe it has to wait for next year, but is there anything in the by-laws or whatever that requires a minimum level of support from the people who cast ballots? Or is it just "whoever gets the most votes gets the seat"? With four candidates, it's possible for someone to win with as little as 25% of the votes. (Well, 25% + 1 vote, but close enough.)

Perhaps it's not a big deal this year, but this could be a real problem if there were 10 candidates.

It would be great (IMO at least) if there was a minimum required to win and a system for ranked-choice or run-offs if no one achieves the minimum. That adds complexity, but it also ensures that the person elected adequately represents the community and isn't actually an unrepresentative voice that wins due to vote-splitting among more representative choices.

**Comment by hackygolucky** [comment]
It is too late for this year @Trott, but yes, I'd had a few conversations about this same concern. I think it's worth opening as a separate issue and discussing further for changes, but there is not currently a minimum level of support set. It's sheer ballot count.

**Comment by joshgav** [comment]
@hackygolucky I have the same issue as @addaleax, signed in with GitHub and also verified at https://identity.linuxfoundation.org/user/me/hybridauth that GitHub login is associated with me. Can you help? Thanks!

FYI all the URL to vote is https://vote.linuxfoundation.org, took me a bit to find it in the OP ;)

/cc @nodejs/collaborators - don't forget to vote by Monday!

**Comment by hackygolucky** [comment]
@joshgav Just emailed you with a fix 💃

**Comment by matthewloring** [comment]
@hackygolucky This issue seems to be affecting me as well.

**Comment by joyeecheung** [comment]
@hackygolucky The website shows "You are not eligible to vote in this election." for me after I logged in with GitHub too. Maybe the system doesn't check the eligibility using the GitHub account at all?

**Comment by hackygolucky** [comment]
@matthewloring @joyeecheung I'm emailing you now each based off of your GitHub profile provided email addresses for fixes 👌

**Comment by hackygolucky** [comment]
Hey folks!

If you're a contributor to Node.js and you're having trouble voting, the first thing you should do is to check when you registered for membership last. Our individual memberships expire after one year, but you can sign back up with the contributor membership code(ping me if you need it). If, after checking that and you are getting 'not eligible to vote in this election', it means our db is being slow on your renewal and I just need to poke an admin to move it along. Thanks!

**Comment by williamkapke** [comment]
Thanks everyone!
