### ISSUE TITLE
Q&A w/ @williamkapke on Individual Membership Candidacy

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/board#43]
This thread is for asking @williamkapke questions regarding [his run](https://www.youtube.com/watch?v=zPBOkqclJFc&feature=youtu.be) for the 2017 Node.js Foundation Board of Directors.

**Comment by nebrius** [comment]
Hi @williamkapke,

Thank you for running for the Node Foundation community seat! To help me and others get to know you better, I have a set of questions that I'm asking all candidates, listed below. I look forward to your answers!

1) How did you get involved in the Node Project?

1) What does inclusivity and diversity within the Node project look like to you? How would you work with the board to increase inclusivity and diversity within the Node project?

1) How would you work with the board to increase international participation in the Node project?

1) What do you think are the pros/cons about the separation of powers/responsibility between the TSC/CC and the Board? How would you improve it?

1) What do you think is the greatest weakness in the Node Project? How would you work with the board to fix it?

1) What do you think is the greatest strength in the Node Project? How would you work with the board to preserve it?

**Comment by williamkapke** [comment]
Hey @nebrius! Great questions.

> 1. How did you get involved in the Node Project?

I started using Node in 2010. When looking for help- I went to IRC. I eventually started helping answer more questions than I asked! I spent many years assisting others in the community this way and only monitored the action on the Node Project... but that changed just over a year ago. I shifted to actively participating within the Node.js GitHub organization with a focus on making it easier for others to do the same.

> 2. What does inclusivity and diversity within the Node project look like to you?

At the Project's level, I believe the way to increase inclusivity and diversity is to continue to increase openness and transparency. We should strive to remove the concept of "insiders" (select individuals with non-public/historical context). I want to lower the barrier to get involved by making as much information available as possible (more on this in the Answer to 3).

> How would you work with the board to increase inclusivity and diversity within the Node project?

A board's role is to identify issues, investigate solutions, and to support solutions. The Board has started gaining awareness, is in the process of assigning experts (via the Community Committee), and now needs to make sure the Committee has the resources and support it needs to be successful. I will drive _proactive_ communication... a vital pillar to avoiding delays and setbacks on initiatives that can quickly deflate momentum. I want to ensure there is an adequate budget dedicated to initiatives and that is not hindered by any technical constraints.

> 3. How would you work with the board to increase international participation in the Node project?

I want to advocate for more financial support for international events and to host Code and Learn _type_ of events along side them that are focused on the website and documentation. I think improving these resources will significantly increasing the international user base.

Additionally, I am a big advocate for providing captions for video/audio content. I write and add them to videos I make public. I do not speak other languages well enough to provide them in anything other than English- but by providing an accurate English version, I extend the audience to the hearing impaired and I open the _possibility_ that they can be translated. The Node Foundation produces many professional videos that are great resources of information for the community. I want to push them to provide these same efforts to all of their videos and to promote this initiative throughout the community.


> 4. What do you think are the pros/cons about the separation of powers/responsibility between the TSC/CC and the Board?

I think this separation is a great thing. I think having dedicated groups of people that are focused on their individual topic's needs-- is a win.

My hope is that there will be a significant amount of people that are involved across the groups to help avoid the concept of "us" and "them." @nebrius-- I think you will serve as a great example of this!

> 5. What do you think is the greatest weakness in the Node Project? How would you work with the board to fix it?

The lack of communication is the Achilles heel of the project. While the Technical side of the project goes to great lengths to publish their work in an open and transparent way- Board's hasn't put much of an emphasis on it.

Here's some things I'd like to assist making better:
- Getting the published version of our governing documents up-to-date
- Limiting the topics that can be discussed outside of a public meeting
- Having the Board meeting times and agendas published ahead of time
- Making sure the Board meeting audio is made available and of adequate quality
- Getting the meeting minutes published

> 6. What do you think is the greatest strength in the Node Project? How would you work with the board to preserve it?

The amazing adoption and ease-of-use! Many of the initiatives above will help preserve and/or increase these... but additionally, being on the board will allow me to work with the Marketing Committee to offer more efforts to the Board that will promote Node and attract more people to try it out!

**Comment by jasnell** [comment]
Just two quick questions from me: (a) In your view, what is the primary role of the Board in the evolution of the Node.js platform and (b) as an individual board member, what would be one thing you'd hope to accomplish over the next year?

**Comment by Fishrock123** [comment]
Two questions (for each of the candidates):

@williamkapke:

1. How will you communicate with broader Node community you could be representing? What would be the primary avenue for questions and comments to yourself and to the board through yourself?
2. How would make future Individual Directors more effective, even continuing past the current term?

**Comment by williamkapke** [comment]
@jasnell
> In your view, what is the primary role of the Board in the evolution of the Node.js platform

The Board should:
- **Explore**: ... continue to seek new uses/environments where Node outshines other platforms.
- **Expand**: ... shine the spotlight on these new areas-- marketing and highlighting them to bring awareness and proof-of-performance that will grow adoption (and the contributor base!).
- **Support**: ... most importantly-- deliver resources to new __and existing__ initiatives while monitoring progress.
- **Protect**: ... make sure the community is safe.
  - Physically & Mentally (Code of Conduct, Inclusivity, Diversity)
  - Licensing/Legal issues.
  - Response to vulnerabilities.

> as an individual board member, what would be one thing you'd hope to accomplish over the next year?

Getting the Node.js Foundation house in order. The Foundation is still fairly new. In the beginning, it had some major tasks that needed all the attention-- namely: Merging the io.js project back to node. We're past that now! We need to get our processes in place and structure(s) lined up to ease new (and old) Collaborator confusion and frustration. This will be vital to the success of the Community Committee and their initiatives. Communication needs to flow more freely. Keeping "black boxes" in the org chart will continue to cause problems.
<sub>BTW, thanks for all the help you've given on last year's efforts!</sub>

@Fishrock123 
> How will you communicate with broader Node community you could be representing? What would be the primary avenue for questions and comments to yourself and to the board through yourself?

As mentioned in my video <sup>[here](https://youtu.be/zPBOkqclJFc?t=3m3s)</sup>, I believe a new Board repo fits in perfectly with our current processes and culture. It provides an open dialog for discussion that will stick around for people to reference.

Additionally, I will be at several events/conferences/meetups (invitations welcome!) speaking to the community and listening to feedback. I would likely encourage them to open an issue on the Board repo so the thoughts/opinions are shared beyond JUST ME. If they are not comfortable doing so, I'll offer to open one on their behalf.

>How would make future Individual Directors more effective, even continuing past the current term?

_All_ of the efforts I give to the Node Community (many listed above)... are geared towards making our fellow volunteers _more effective_... including the Board members! 😃
