### ISSUE TITLE
Rename this repo to `Board` and assign ownership

### ISSUE THREAD

**Issue by williamkapke** [nodejs/board#48]
The Individual Directors, @ashleygwilliams and myself, would like to have a "Board" repo for collaboration with us & and any other willing participants of the Node.js Foundation Board of Directors. I suggest we repurpose THIS repo for it since it already deals with the topic. The bit of membership information that exists here today will stay.

With this, we would be the custodians of the repo. It will be our duty to keep the information up-to-date and coherent for the community. Additionally, we will rely on the assistance of @mikeal and @hackygolucky PLUS any Moderation group that may be formed in the future.

One stipulation I want to call out is that during an election period, if an exiting representative is pursuing re-election, they must not edit/moderate any issues regarding the election. They may, however, participate in them as any other community member would be allowed.

As this repo is not currently under the governance of any particular group except, by default, The Board- I am presenting this post to provide an OPEN notification of the desire to complete this action giving the community an opportunity to vocalize any possible objections. I will leave this open for a minimum of 1 week.

**Comment by mikeal** [comment]
This is a very good idea :nerd_face:

**Comment by nebrius** [comment]
I really like it too, I'm excited to see what comes from it!

**Comment by williamkapke** [comment]
Done! 🎉
