### ISSUE TITLE
NodeConf

### ISSUE THREAD

**Issue by mikeal** [nodejs/board#5]
So, I own the Trademark for NodeConf and generally administer the organization and help out with events where I can.

Every NodeConf is run by an individual or company independent of myself (except for the ones I run personally, obviously). We've grown the list of NodeConfs by offering some support and the use of the term under a few conditions:
- NodeConf ONE-SHOT -- Event must be single day, single track. Organizers need only sign up on the organizers repo.
- NodeConf -- Event should be at least 2 days and be of high production value. Organizer must have previously attended a NodeConf (Either US or EU usually).

There are two other events that have previously only been run by me: NodeConf SummerCamp and NodeConf Adventure, which are both unconference format events.

_If_ we decide to bring NodeConf in to the foundation we could put a bit more organization around helping to promote these community events as well as extend the brand to any new events that address audiences we have not previously reached. We could also add some conditions that offer incentives for members to participate: 10% off tickets for individual members and 10% off of sponsorships for corporate members of the foundation.

**Comment by guyellis** [comment]
:+1: Very generous of you to consider this.

**Comment by digitalsadhu** [comment]
I'm not sure I would have considered running a conference if it wasn't for my discovery of "NodeConf Oneshot". Having some tips, a template website etc made it accessible and easy to get started. :+1: 

That said, there are things to improve. More tips and suggestions, improving the website template etc. If moving under the foundation might provide additional resources for this sort of thing I'm all for it. :heavy_check_mark:

Would there then be a working group for NodeConf? 
That would be something I'd like to participate in. :question: 

One further thing I would like to mention from my experience is that Oneshot has a bit of a branding issue. I struggled with convincing others that we needed to use "NodeConf Oneshot Christchurch" or just "Oneshot Christchurch" as the name/title of the event. Almost everyone ended up referring to the event as just "NodeConf Christchurch"
People felt (strongly) that "Oneshot" events are good for trying to build community around node and that many of the people you are trying to attract are completely new to node and have no idea what "Oneshot" is or what it means. Furthermore, people felt that "NodeConf Oneshot Christchurch" is too long/too much of a mouthful... :memo:

**Comment by mikeal** [comment]
> Would there then be a working group for NodeConf? 

Yes, but the mechanics of where that would live aren't quite obvious yet. It wouldn't live under the main project as a WG under the TSC because it has no clear path to being a "core" WG. The Lifecycle charter has an allowance for us to create new top level orgs but each one will have to get board approval until we come up with a better way.

Basically, we'll have to talk about what the ideal structure is and then present that to the board along with a proposal to put NodeConf in the foundation. Whatever the structure is though, you're welcome to participate :)

> One further thing I would like to mention from my experience is that Oneshot has a bit of a branding issue. I struggled with convincing others that we needed to use "NodeConf Oneshot Christchurch" or just "Oneshot Christchurch" as the name/title of the event. Almost everyone ended up referring to the event as just "NodeConf Christchurch"

I've noticed this a little bit as well. The reality is, it's fine for the events to be referenced as just "NodeConf CityName" because there's never going to be overlap between one of these and a larger NodeConf because those tend to have country or region names (NodeConf US, NodeConf EU, NodeConf India, etc).

I think if there were a better website template it could call them "ONE-SHOT" but sort of downplay it in terms of branding. The only thing we really need to convey is that these events are simpler one day events (that hopefully seem more accessible because they are more intimate) and the other big "NodeConf" events are something more of a massive production.

**Comment by digitalsadhu** [comment]
I'd be happy to turn our Christchurch site into something more generic that could be used by anyone. Would this be desirable?

**Comment by bnb** [comment]
+1 to NodeConf being absorbed into Nodejs. I would be willing to do front-end development, more trivial server-side development (as I'm not quite as skilled at it), and marketing/communications for NodeConf no matter what, but I think it would be _very_ beneficial to Node.js to have NodeConf as an official conference; in my experience with io.js' community, this seems like it would be best handled by a NodeConf WG.
