### ISSUE TITLE
PR board minutes for 2017-02-13 Board Meeting

### ISSUE THREAD

**Issue by williamkapke** [nodejs/board#56]
@mikeal, we would like to get a PR up of the _proposed_ public 2017-02-13 Board Meeting minutes at least 36 hours before the meeting. Please let me know if I can help.

**Comment by mikeal** [comment]
Let's discuss that practice in Monday's board meeting. I'm fine with it in theory but I want to run it by the board to make sure it's something they are comfortable with.
