### ISSUE TITLE
Clarify By-Laws WRT Community Committee

### ISSUE THREAD

**Issue by williamkapke** [nodejs/board#57]
1) The **type** of committee the Community Committee ("CommComm") _is_-- is not explicitly stated anywhere. The By-Laws define 2 types: Board Committees and Member Committees. The TSC is a Member Committee. I assume the CommComm was enacted under:

> **Section 5.4 Committees of the Members**
> (a) From time to time, the Board may establish Member Committees in addition to the
Technical Steering Committee (as described in paragraph (b) below). Membership attendance
and voting rights in all Member Committees shall be as specified in Article II, and any such
Member Committee may operate under such further rules of process as it may propose and
which are approved by the Board. 

2) The TSC is excluded from the requirement that its committee members must be `Foundation Members`:

> **Section 2.8 Participation**
> Participation in the Technical Steering Committee and development projects sponsored by the Foundation **shall not be limited to Members** ... [snip]

3) A benefit of Silver Membership is the opportunity to place a representative on Member Committees:
> **Section 2.5 Privileges of Silver Membership**
> ... [snip]
> (c) appoint one voting representative, on a one vote per Member basis, to each Member
Committee (for example, a Marketing Committee, Finance Committee, etc.) other than the
Technical Steering Committee;

I think we probably want CommComm to have the same exclusions the TSC has above.

/cc @nodejs/community-committee

**Comment by mikeal** [comment]
These outlines for different committee types are there so that the board can quickly form committees *without* passing an entire charter for each. When the board does pass a charter, as it has for the Community Committee, it can outline whatever restrictions and structure it wants, it doesn't have to fall exactly in line with any of the pre-defined definitions in the bylaws.

**Comment by williamkapke** [comment]
> can outline whatever restrictions and structure it wants

right- we just need to get this part done or it falls to the rules above.
(assuming CommComm wants this 😉 )

**Comment by williamkapke** [comment]
@nodejs/community-committee I added a cc-agenda label to this so we can discuss it in our next meeting.

**Comment by mikeal** [comment]
> right- we just need to get this part done or it falls to the rules above.

I don't think this is accurate. The board passed a charter that outlined a committee that clearly doesn't operate within the restrictions of a member or board committee.

I can refer you to outside counsel to clarify if you wish but I haven't heard anyone interpret the charter or bylaws the way you have here.

**Comment by williamkapke** [comment]
I would like the Linux Foundation to follow up with legal counsel to clarify.

@mrhinkle @hackygolucky

**Comment by mikeal** [comment]
@williamkapke just email your question to Andy and CC us :)

**Comment by hackygolucky** [comment]
@williamkapke I think we had comment from legal in one of the recent Board sessions on this. Was it a sufficient answer to close this issue?

**Comment by williamkapke** [comment]
The outcome was that CommComm is an `undefined` type of Committee and that the TSC should probably just be an `undefined` Committee too- but that would require changing the By-Laws... and doing it for something that isn't _currently_ causing any problems.

<del>Maybe some day a Silver Member will cash in on their rights and place someone on the TSC and then it'll be of concern ;) </del>
EDIT: I just remembered that the language says the TSC is excluded from that right.

SOOoo AFA CommComm is concerned. This topic is not a problem.
