### ISSUE TITLE
Cost of Membership

### ISSUE THREAD

**Issue by guyellis** [nodejs/board#6]
Following on from https://github.com/nodejs/membership/issues/3 this is to discuss the cost of membership.

Proposed using Linux Foundation model:
- $25/year for Students
- $99/year for Everyone Else

Also discussed free or $1/year membership for core contributors.

**Comment by Morgul** [comment]
Alternative suggestions of cost for contributors:
- $5/yr
- $25/yr

As discussed, $25/yr might have some push back. I also added a suggestion for $5, it feels a little more meaningful than $1 (which to me seems still in the 'why bother' range), but it still feels under the threshold where there might be community push back.

**Comment by Morgul** [comment]
Additionally, do we want to have these prices be minimums? Say I want to sign up to be a member and donate a little more at the same time, could I roll it all up into a $150 payment? Or would it need to be a $99 membership fee, and a $51 donation? Is there any legal ramifications (say for tax purposes, etc?)

**Comment by jasnell** [comment]
Should the discounted cost for contributors be persistent year to year or only apply to the first full year after becoming a contributor? I'm generally inclined towards the latter.

**Comment by mikeal** [comment]
So, from the meeting it sounded like we were in to this cost structure:
- Student ($25/yr)
- Individual ($99/yr)
- Active Contributor (free)

We need to define "Active Contributor" as "Anyone who is a member of one of the GitHub orgs in the foundation" because there will eventually more than one org "in" the foundation.

**Comment by Danese** [comment]
Wikimedia defines it as "anyone who has contributed in the past year", which in practice means "anyone who has logged in as an editor in the past year" (because they have that data).

Our bar may be higher or lower. Just suggesting this as a way to make sure you have to be currently active to vote.

D

**Comment by mikeal** [comment]
@Danese I like that, we can get that data out of GitHub as well -- although it isn't necessary for the first round because the entire org is less than a year old :)

**Comment by Danese** [comment]
Agreed.

Another point? Although I get why you wish to avoid the hassle of nominations, we've found that requiring a statement of intent really helps people decide who to vote for...usually these include a few pro forma questions such as "Why do you want to serve on the Board?" "Do you have previous experience serving on a non-profit board?" and "What lasting impact would you like to see resulting from your Board service?"

It's also important to give the candidates a realistic idea of the time commitments and any travel commitments (if for example there are two Board Retreats per year).

D

**Comment by mikeal** [comment]
> Although I get why you wish to avoid the hassle of nominations,

Sorry, I didn't explain this very well. I didn't want to have us maintain a list of those nominated but instead require that each person make a statement themselves about why they think they are a good candidate.

I'm now realizing that this system favors people with more existing pull on social media though so we should probably do a simple nomination system where people create an Issue on GitHub answering questions like you suggest and that can be used as a simple list of registered self-nominations.

**Comment by guyellis** [comment]
Those are good question @Danese 

@mikeal I was thinking of a single wiki page that all candidates could edit so the Q&A for all would be in one location.

**Comment by bnb** [comment]
@guyellis I think the wiki is a good way to go. The wikis in GitHub repos are essentially repos without the need for PRs. Having a form, essentially set up like a website with a flow through the pages to follow the steps, would be pretty easy, and it would allow an index of all members, applications, and statuses.

**Comment by mikeal** [comment]
Historically we haven't had a lot of luck getting people engaged with wiki's on GitHub. The wiki feature of GitHub lacks all the features we tend to use to help get people engaged (comments, notifications, etc) and we tend to only use it for documentation which we rarely update and permalink to (like the hangout instructions for TSC calls).

**Comment by guyellis** [comment]
Good point @mikeal - the reason I'm reading this comment of yours now is because of notifications. I wouldn't have been aware of a change on a wiki...

**Comment by bnb** [comment]
@mikeal After considering you comment about GH Wikis and reading your post again, the GitHub issues for membership seems like a good idea to me. As you suggested, Issues have notifications, which is important to get people voting. 

Would you want to use this repo for that? I'm going to give the structure for this a shot now.

**Comment by Morgul** [comment]
@bnb I'm pretty sure that the intention isn't for membership applications to be done via GH issues, but rather running for the board seat that members will get to vote on. @mikeal am I right in that?

**Comment by bnb** [comment]
@Morgul  [This](https://github.com/nodejs/membership/issues/6#issuecomment-106266917) is where I got that idea from:

> so we should probably do a simple nomination system where people create an Issue on GitHub answering questions like you suggest and that can be used as a simple list of registered self-nominations.

**Comment by bnb** [comment]
@Morgul [wrote](https://github.com/nodejs/membership/pull/9#discussion_r31396251):

> I'm a little uncomfortable with the idea of having an application for membership; provided I'm willing to give the foundation the requested amount of money per year, I should be able to join, quite literally with no questions asked.

Posted here to have maximum visibility.

**Comment by Morgul** [comment]
@bnb I'm pretty sure that was talking about the board nominations...

@mikeal, some clarification?

**Comment by Burstaholic** [comment]
@Danese @mikeal It looks like the conversation from #8 somehow bled over into this issue.

I am curious - @mkdolan, is there a connection between code contributions to Linux and Linux Foundation membership?

Clearly, many people probably will want to be members who won't directly contribute code, and it does seem nice to give contributors some kind of concrete reward (just to get the obvious caveats out of the way).

**Comment by mkdolan** [comment]
Our Foundations often do different things for the developers. The LF individual membership is open to anyone, contributor or not. We do a lot of other things to recognize developers… Some of our projects do novelty things (e.g. have coins created, “Code is the coin of the realm.”, special t-shirts or hoodies, e.g. a t-shirt with all the contributors to release v1). 

Does this help? The cost is entirely up to whatever the community decides… we’ll ask the Board to authorize the expense of funds (the auditors require it), but I’ve never seen it even debated whether to approve the plans put forward.

**Comment by mkdolan** [comment]
I should also add the bylaws we just reviewed/approve with the legal team now include an Individual Member Director so keep in mind those who sign up will be electing that person. We will recommend the Board defer that election for some time after the first initial Board meeting, but wanted to put that on everyone's radar too. At some time it would be good to discuss and get direction on the logistics and process the community will follow for the Individual Director election.

**Comment by guyellis** [comment]
@mkdolan Thanks for that clarification. Good to know hear that the funding from the corporations is used by other foundations to recognize contribution. Correct me if I'm wrong: Does this also mean that the membership doesn't need to be self-funded and if not does the LF run a loss with the student membership at $25/year?

**Comment by mkdolan** [comment]
I don’t have access to those financials, but I’m going to guess $25 does not cover much of our expense… so yeah, you’re likely looking at breakeven/loss at that price point. Our goal is to encourage students to engage with the community so it’s worth our investment strategically.

**Comment by bnb** [comment]
@mkdolan As a student myself, I am very, very glad to hear that from you - knowing that we are worth something to the foundation based on what we can give is unbelievably encouraging. Thanks.

Edit: spelling.

**Comment by mkdolan** [comment]
I think of projects in terms of decades, not 6-24 months. In that view, you should all be thinking about ways to grow, foster and teach the next generation how to engage, work and successfully develop and contribute to the communities you participate in - Node.js and others. I see a lot of effort all over this project with people investing time and energy in this direction - which is extremely encouraging and hopefully welcoming to new participants and contributors. Students are the next generation and the developers leading projects today will be development managers (or higher) eventually and they’ll be asked to hire energetic university hires under them who know the codebase. It’s a supporting cycle that’s important for everyone involved and the health of a project that will last a decade or more. The same thing has been true for Linux for a long time. Projects that don’t, well they tend to lose touch with new approaches, techniques, etc. as well and adoption slows and eventually wanes as talented hires are deployed to other, more leading edge alternatives.

Hopefully that explanation is short enough to not fall into the TLDR category :-)

**Comment by bnb** [comment]
@mkdolan Yes, it was short enough - and also a fantastic, joy-inspiring piece that makes me proud to be a student, and validates it despite all the people who say college isn't worth it. Thank you, thank you, thank you.

**Comment by Morgul** [comment]
So, to kinda steer back towards the topic, it sounds like the $99/yr regular and $25/yr student is pretty much agreed upon. 

Free for members of the GitHub org, with renewal price to be be determined?

**Comment by bnb** [comment]
@Morgul Thanks for bringing up renewal. What are people's thoughts on renewal cost? Should it maintain the original price, or go down from there by a percentage?

Personally, I think having the original price be a flat fee sounds good. Keeping that as a steady funds stream will help the Foundation, and it will weed out those that want membership without being serious about it on a professional level.

Also, are we going to have organizational membership? I know some big companies would probably like to sponsor - should we do a tiered membership for them? Do we take into account the size of the company? What would be the price range for them in tiers or, if we decide against tiers, all together?
