### ISSUE TITLE
Discuss alleged misconduct of our community manager

### ISSUE THREAD

**Issue by williamkapke** [nodejs/board#62]
This serves to notify the community of my intent to raise the issue of alleged misconduct of our community manager during the board's next private session. The details of the matter beyond this information will only be made public with approval of the board.

**Comment by mikeal** [comment]
I don't see how this issue could be used for discourse about this without pointing to the concerns in question.

I'm going to assume this is about me and about this thread https://github.com/nodejs/TSC/issues/259 (note that you'll need to expand the details of the comments as they have been collapsed at @jasnell's request).

I'm open to any criticism people might have over my comments.

**Comment by jasnell** [comment]
I assume this issue can be closed now?

**Comment by williamkapke** [comment]
@jasnell Not at all. Unfortunately, a resolution has not been delivered on this.

**Comment by jasnell** [comment]
Ok let's discuss offline

**Comment by bnb** [comment]
@williamkapke Since Mikeal is no longer technically the Community Manager, can this be closed? One year without any forward progress is a strong indicator that there won't be progress, especially since the issue is technically invalid.

**Comment by williamkapke** [comment]
The details on this are private so it is tough to comment on. He, without reading the details submitted, implicated himself causing people to believe he was the focus of the deliverable on this.

The actual deliverable was not been addressed, at the time, for reasonable reasons- and remains unresolved to date.

**Comment by bnb** [comment]
@williamkapke what is the path to resolution of the deliverable, then?

**Comment by bnb** [comment]
If there's not a path to resolution of the deliverable, then I don't really see a reason for this to continue to be open.
