### ISSUE TITLE
Section 2.5 c) might need to be updated to include Community Commitee

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/board#65]
According to [2.5 c)](https://github.com/nodejs/board/blob/master/by-laws.md#section-25-privileges-of-silver-membership) member organizations are currently able to assign individuals to the Community Committee. I don't believe this is intentional.

/cc @nodejs/community-committee

**Comment by nebrius** [comment]
Agreed, this looks to me like it slipped through the cracks when chartering CommComm.

**Comment by williamkapke** [comment]
Glad to see people reading the by-laws :)

Please check out #57 for info on this topic.

**Comment by williamkapke** [comment]
I think #57 has the answers you're looking for- yes?
Re-open if I have misunderstood.
