### ISSUE TITLE
Board vote to allow community member on board

### ISSUE THREAD

**Issue by guyellis** [nodejs/board#7]
Need to add an item to the first board meeting agenda to vote on changing the By-Laws to allow a community representative on the board.

This issue is to get this item onto the board's agenda.

**Comment by mikeal** [comment]
@mkdolan we have other threads going for how the membership is structured and how the individual membership can vote to elect a representative. Can you let me know if we are missing any information we'd need in order to have the board consider this change to the bylaws and take it to a vote?
