### ISSUE TITLE
Education Community Manager resigning

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/board#71]
​To the hardest workers in Node.js,
   
It is with my greatest appreciation for the Node.js collaborators that I write to inform you of my resignation from my position as Education Community Manager. My last day will be ​this ​Friday, December 15. I have a new​ opportunity that ultimately aligns more closely with my career goals and offers more direct control in achieving my goals.

​The certification development will continue under [Annie Fisher at the Linux Foundation](mailto:afisher@linuxfoundation.org). The rest of the education and community management responsibilities are still being discussed. Please send those scoped questions to [Mark Hinkle](mailto:mhinkle@linuxfoundation.org), Node.js Foundation Executive Director. 

I am still ​very much going to be around contributing to the Node.js project and the JavaScript ecosystem on my own time. I look forward to continuing to remove barriers for  project contributors especially through navigating the blurry lines of the foundation’s scope, connecting folks, and improving the dialogue of collaboration so that we all can keep doing what we enjoy doing in Node.js.​

​I am happy to answer any and all questions, so please don't hesitate to contact me. I want to make sure our community members feel taken care of. I am not going to be writing any Medium posts ;).

Best,

Tracy Hinds
Education Community Manager
Node.js Foundation
@hackygolucky

cc @nodejs/members

**Comment by BridgeAR** [comment]
I want to thank you for all your work and your dedication that you put into improving the community further! It is sad that you leave but totally understandable. I wish you all the best in your new position and hope our ways will cross again.

**Comment by watson** [comment]
I'm sad to see you go. It's been a real pleasure getting to know you and you've been a driving force in the foundation. But I know all good things must come to an end and I wish you all the best in your new endeavours and I hope to run into again soon. Best of luck ❤️

**Comment by mhdawson** [comment]
Thanks for your hard work in the Node.js project and from what I hear we'll still see you participating.  I'm sorry to see you go but our loss will be a gain for the new organization you are joining.

**Comment by Qard** [comment]
Thanks for all you've done for the Node.js community, and good luck with what comes next! ❤️

**Comment by MylesBorins** [comment]
Thank you for all the amazing work Tracy

Your absence will be felt.

**Comment by gr2m** [comment]
Thank you for everything Tracy ❤️

**Comment by rosskukulinski** [comment]
Thank you for everything you've done for Node and it's community over the years.  I look forward to seeing more great things from you.  Keep being awesome, Tracy.

**Comment by gireeshpunathil** [comment]
Tracy, I don't  have much insight on your work on certification development, but have seen your excellent work on mediation, moderation and de-escalation through some of the recent work items. Snuffing the flame without hurting both the parties is a wonderful skill, and you are great at that. Wishing you a great success!

**Comment by joyeecheung** [comment]
Thank you for everything, Tracy. Wish you all the best!

**Comment by fhinkel** [comment]
Tracy, you did fantastic work. Thank you for everything ❤️ . You'll be greatly missed. Wish you all the best for the future and hope to see you around.

**Comment by Tiriel** [comment]
Wow. You were one of the first persons from the Node.js community I followed the news from, and I was always amazed by the community work you put together, wether on education, mediation, or motivation. As it was already said, I think your (partial, I hope) absence will be greatly felt.

Wish you all the best for your next adventure!

**Comment by watilde** [comment]
Thank you so much for your hard work and great actions. Good luck on your new journey :)

**Comment by evanlucas** [comment]
Tracy, thanks for everything you have done for Node.js and the community around it! Good luck with your new opportunity!

**Comment by a0viedo** [comment]
Thank you for your awesome work, Tracy :heart:

**Comment by dshaw** [comment]
@hackygolucky Thank you for all the work you've done to help drive the efforts of the Node.js Foundation. I'm certain we would not be where we are today without you. Launching the @nodejs/community-committee is a crowning achievement which I'm happy to see continue to grow and blossom. 🙏

I look forward to continuing to collaborate with you in the community. Best of luck on what's next.

**Comment by ghost** [comment]
thank you for your essential work in establishing the community committee! i hope to be working together with you in the future

**Comment by shiya** [comment]
Thank you for all your work, Tracy! Happy for you about what you have ahead! :)

**Comment by obensource** [comment]
🙌 TRACY! 🙌

Thank you for being such an incredible, people loving, positive force in Node.js and everywhere else! You're an inspiration to everyone who has the privilege of working with you, to any capacity. 

I'm super excited to see you shine in the next step of your journey, and look forward to still seeing you around the Node.js/JS community! ❤️❤️❤️

**Comment by NickNaso** [comment]
Tracy, thank you for your fantastic work. I don't know you personally, but I followed what you did for Node.js community and how you cared about its values, so for me you will miss a lot. Good luck for your new challenge I really hope that all will be the best for you.

**Comment by othiym23** [comment]
Thank you for all you've done for Node.js, the Foundation, and the JavaScript community. I've only gotten to work with you directly on a few small things but those have all been a pleasure. I have deeply appreciated your level head and steady cool at many of the spicier moments around Node in the last few years. We all owe you a lot.

I'm excited to see what you do next and hope we'll continue to have opportunities to work together!

**Comment by xeodou** [comment]
Thank you for all you did, Tracy. And thank you for everything you did for connect the China Nodejs community with the foundation.

**Comment by sarahmeyer** [comment]
Thank you so much for everything. I feel like you're the reason I'm in the Node community at all, however peripherally, and I doubt I'm the only one who feels that way. It makes me so happy to hear that you're moving on to bigger, better challenges, but you will absolutely be missed. Can't wait to see what comes next for you. ❤️ ❤️ ❤️

**Comment by bnb** [comment]
Thanks for literally *everything* you've done for the Node.js community, Tracy - from your involvement in the broader community, to being deeply involved in the Community Committee, to being an invaluable resource for literally every human being contributing to the project.

I look forward to continuing to work with you driving improvements around Node.js communities - both inside and outside of the core project.

Excited to see what's next, and I wish you the best of luck with it. ❤️
